services:
  - type: web
    name: geoescrituras-backend
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free