services:
  - type: web
    name: geo-escrituras
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    autoDeploy: true